markdown: kramdown
permalink: pretty
defaults:
  -
    scope:
      path: "" # anywhere
    values:
      layout: default
collections:
  albums:
    output: true
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
