markdown: kramdown
permalink: pretty
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
defaults:
  -
    scope:
      path: "" # anywhere
    values:
      title: Aaron Irwin
      layout: default
collections:
  albums:
    output: true
